### ISSUE TITLE
Exams CRUD

### ISSUE THREAD

**Issue by tsvetan-ganev** [uni-ruse-software-engineering-2017/exam-registration-backend#3]
Implement the following:

1. Create exam
2. Delete exam
3. Edit exam information
4. Apply for exam (as a student)
5. Cancel exam application (as a student)
6. Approve / reject student (as a professor)

REST endpoints:

1. `GET /exams` - list all exams in the system
2. `POST /exams` - create a new exam
3. `DELETE /exams/{id}` - delete an exam by ID
4. `PATCH /exams/{id}` - edit an exam
5. `POST /exams/{id}/apply` - apply for an exam (as a student)
6. `POST /exams/{id}/cancel` - cancel exam application (as a student)
7.  `PATCH /exams/{examId}/student/{studentId}` - change student status (as a professor)

**Comment by amitev** [comment]
isn't DELETE method appropriate for canceling exam application?

**Comment by tsvetan-ganev** [comment]
@amitev, I'm not sure if we should actually delete the application, or just change it status to "cancelled". If we would delete it, the `DELETE` method is more appropriate.

**Comment by amitev** [comment]
Then the path should be something like

PATH /exam/{id}/participatation/{id}/status

**Comment by tsvetan-ganev** [comment]
Update:

- [x]  `GET /exams` - list all exams in the system
- [x]  `POST /exams` - create a new exam
- [x] `DELETE /exams/{id}` - delete an exam by ID
- [x] `PATCH /exams/{id}` - edit an exam
- [ ] `POST /exams/{id}/apply` - apply for an exam (as a student)
- [ ] `POST /exams/{id}/cancel` - cancel exam application (as a student)
- [ ] `PATCH /exams/{examId}/student/{studentId}` - change student status (as a professor)
